---
title: "Stroop Task"
author: "Marcello Gallucci"
date: "`r Sys.Date()`"
nickname: digitspan
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mcdocs)
mcdocs_init()
```

# Stroop Task

The Stroop test shows a series of color names colored with different colors. The participant should name (select in a multiple choices answer) the color of the font in which the word is shown. The words are presented with a congruent color ("Red" shown in red) in half of the trials, and in an incongruent color ("Red" in green) in the other half. Colors are red, blue, yellow and green.

In this implementation, 28 trials show congruent color-word trials and 28 incongruent ones. One can add or remove trials or duplicate the task for longer experiments.

The order of presentation of the stimuli is randomized.

The test is implemented with a minimum of javascript code. It does not require any JS library and does not depend on the format of the survey it is included.

## Import in qualtrics

Download the `stroop_task_Eng.qsf` and login to your qualtrics account. Create a new project and select the to import an QSF file.

`r mcdocs::pic("pics/stroop1.png")`

Choose your file and hit `Create Project`.  If everything goes as planned, your are ready to go. 

## Use it in an existing project

It is likely that you want to import the test into an existing project, with other tests and questionnaires. Due to some limitations in qualtrics system, you cannot save the survey into the library and import it in another project. This operation would not work because if you save a survey in the library, loop and merge setup of the survery will be lost. 

Thus, simply import the task using _Copy from Existing Survery_ function: Add a block, then 

`r mcdocs::pic("pics/ds4.png")`
 
 and then
 
 `r mcdocs::pic("pics/ds3.png")`


## Structure of the task

At the moment the task implements a block of 56 words (color names), half congruent and half incongruent. The displayed words and their color are defined in the `loop and merge`, in the `stroop stimuli` block (second block). 

`r pic("pics/stroop2.png")`

`r pic("pics/stroop3.png")`

`Field 2` stores the word to be shown, the `Field 3` in which color should the word be displayed. `Field 4` indicates whether the stimulus was shown in a congruent or incongruent color. The latter field is there to be saved in the dataset. 


## Trials

The present implementation offers the minum set of trials. 4 colors, each shown 7 times in an incongruent color and 7 times with the congruent color. By adding rows to the `Loop and Mege` fields one can increase or decrease the trials shown. Trials are randomized

`r pic("pics/stroop4.png")`

An easy way to increase the number of trials is to copy the whole block `stroop stimuli`.

# Data

`r pic("pics/stroop5.png")`

In the dataset, apart from other variable, the survey saves, for each word-color pair N, the diplayed word `N_stimulus`, the response time `N_time_First Click`, the color of the word `N_stroop_color` and whether the color-word as congruent or not `N_stroop_cong`. The other columns can be ignored.



